background.js
manifest.json
menu/popup_view.js
spec/popup_view_spec.js

The "preview" env has been replaced with "integration".

Remove preview environment

---

spec/javascripts/popup_view_spec.js
src/menu/popup_view.js

Extract URLs with double slashes correctly

---

src/manifest.json

- Fix issue with double slashes in URL (#12)
- Fix staging URL (#13)
- Add support for National Archives (#14)

Release version 1.1.0

---

spec/javascripts/content_links_spec.js
spec/javascripts/external_links_spec.js
src/popup.html
src/popup/content_links.js
src/popup/external_links.js
src/popup/popup.css
src/popup/popup.js

See individual commits for more info!

Various tweaks

---

src/manifest.json

- Support for smart-answers
- Link correctly to placeholder schemas
- Link to business-support-finder app correctly

Release version 1.3.0

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js

The repo is different for frontend/backend, so I've split up the
function that maps these into one for frontend and one for backend.

Fix trade tariff repo names

---

src/popup.html
src/popup/popup.css

This PR has some layout tweaks to prevent scrollbars from showing.

Redesign spacing to prevent scrollbars

---

src/popup/popup.js

This is a temporary solution to make most functionality work after the user clicks a button in the popup.

Temporarily fix the popup after user clicks

---

src/events/ab_test_settings.js
src/popup/popup.js

This PR has some small refactoring and explanatory comments to (hopefully) make the process of A/B testing clearer.
@suzannehamilton

Add some documentation & do small refactorings

---

src/popup.html
src/popup/popup.css

Show A/B testing bar in the middle

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js

Link taxon pages directly to content tagger

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js

Closes https://github.com/alphagov/govuk-toolkit-chrome/issues/65

Simplify base path lookup

---

src/popup.html
src/popup/popup.css

Tiny update for the loading message.

Make the loading message look better

---

README.md

I don't actually have access anymore! I removed myself just before I left.

Remove me from the list of people with release permissions

---

spec/javascripts/content_links_spec.js

Fix tests from adding content data link

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js

Remove unnecessary content data link

---

src/popup/external_links.js

https://trello.com/c/THCRZX2Z/1766-investigate-chrome-extension-for-github-smart-answer-maintenance

Add smart answers links to github flow page/folder

---

package-lock.json
package.json
spec/helpers/helpers.js
spec/helpers/polyfills/String.startsWith.js
spec/javascripts/ab_tests.spec.js
spec/javascripts/content_links.spec.js
spec/javascripts/design_mode_component.spec.js
spec/javascripts/environment.spec.js
spec/javascripts/events/ab_bucket_store.spec.js
spec/javascripts/external_links.spec.js
spec/javascripts/extract_path.spec.js
spec/javascripts/highlight_component.spec.js
spec/javascripts/show_meta_tags.spec.js
src/components/design-mode-component/design-mode-component.js
src/components/highlight-component/highlight-component.js
src/components/show-meta-tags-component/show-meta-tags-component.js
src/events/ab_bucket_store.js
src/events/ab_test_settings.js
src/events/icon.js
src/fetch-page-data.js
src/popup/ab_tests.js
src/popup/content_links.js
src/popup/environment.js
src/popup/external_links.js
src/popup/extract_path.js
src/popup/popup.js

Add a linter to the govuk-browser-extension
To analyse the code for any potential errors or stylistic issues, making it easier to maintain code quality and consistency across the app.
https://trello.com/c/hgBWMrlB/2296-add-a-linter-to-govuk-browser-extension

Add linter to govuk browser extension

---

.github/workflows/release.yml

I forgot these wouldn't get passed directly

Pass secrets to env when getting Chrome version

---

.github/workflows/release.yml

The format is `platform-version.zip`, not `version-platform.zip`

Set build filenames correctly

---

.github/workflows/release.yml

This wasn’t the correct argument

Change `xpi-path` to `file-path`
