alphagov/govuk-browser-extension

src/manifest.json

This includes https://github.com/alphagov/govuk-toolkit-chrome/pull/6 & https://github.com/alphagov/govuk-toolkit-chrome/pull/7.

Release 1.0.0

---

spec/javascripts/popup_view_spec.js
src/menu/popup_view.js
src/popup.html

The old 'www.staging.publishing.service.gov.uk' URL no longer works as it has been removed from Fastly.
Updated to point to 'www-origin.'

Fix staging environment URL

---

spec/javascripts/popup_view_spec.js
src/menu/popup_view.js

The National Archives keeps a history of GOV.UK. This commit adds support for switching between the current site and the index page for the URL on http://webarchive.nationalarchives.gov.uk/.

Allow switching to the National Archives

---

README.md
spec/javascripts/content_links_spec.js
spec/javascripts/extract_path_spec.js
src/popup/content_links.js
src/popup/extract_path.js
src/popup/popup.js

`draft-origin` is able to serve pages from the draft content-store for some formats:
https://www.gov.uk/browse/education
https://draft-origin.publishing.service.gov.uk/browse/education
On certain pages the draft stack will error (search for example, because there's no draft-search).

Add link to draft version of item

---

src/popup/external_links.js

Pages have `businesssupportfinder` rendering-app, but the repo is
`business-support-finder`.

Link to businesssupportfinder correctly

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js

Content items have either a named schema (like "detailed_guide") or a schema name that's prefixed by "placeholder" (like "placeholder_organisation").
This commit makes sure that we link to the `placeholder` content schema for placeholder things.

Link correctly to placeholder schemas

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js
src/popup/extract_path.js
src/popup/popup.css

All pages on GOV.UK have a "Is there anything wrong with this page?" link. The feedback gathered from this is sent to the [support application](https://support.publishing.service.gov.uk).
This commit adds a deeplink to the support app for the current page.

Add link to anonymous feedback explorer

---

spec/javascripts/content_tools_links_spec.js
src/popup/content_tools_links.js

[Trello card](https://trello.com/c/JHMfhXJa)
[SmartAnswers](https://github.com/alphagov/smart-answers) includes a visualise tool to allow content designers to see how the questions and outcomes in a smart answer relate to each other.
This PR adds a link to view the flow visualisation for the current page, if the current page is a smart answer.

Add visualise link for SmartAnswers

---

src/fetch-page-data.js

This script is executed in the main browser thread, not inside the popup. This means it won't necessarily have access to jQuery, since the page where it's executed could be erroring, or just not have it installed.

Don't rely on jQuery being present

---

src/popup/content_links.js

Since info-frontend was made to work with data from the content-store, the /info page works for everything that's in the content-store (+99% now).

The /info page almost always works

---

src/manifest.json

This 'tabs' permission is quite powerful but it shouldn't be needed for
this plugin. Chrome docs say:
The majority of the chrome.tabs API can be used without declaring any
permission. However, the "tabs" permission is required in order to
populate the url, title, and favIconUrl properties of Tab.
https://developer.chrome.com/extensions/tabs
I believe the functionality of the extension only reads from these
properties and doesn't need to populate any of them.

Remove 'tabs' permission

---

src/manifest.json

- Better support for mainstream pages (https://github.com/alphagov/govuk-toolkit-chrome/pull/33)
- Manuals now correctly link to manuals publisher (https://github.com/alphagov/govuk-toolkit-chrome/pull/34)
- Extension now requests less permissions (https://github.com/alphagov/govuk-toolkit-chrome/pull/36)

Release 1.5.0

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js

When selecting "Content Item" from https://www.gov.uk/done/pay-dvla-fine
it was sending the user to https://www.gov.uk/api/content/done instead
of https://www.gov.uk/api/content/done/pay-dvla-fine
This commit aims to solve that issue.

Fixes content api url for /done/pay-dvla-fine

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js

When selecting "Content Item" from https://www.gov.uk/help/cookies
it was sending the user to https://www.gov.uk/api/content/help instead
of https://www.gov.uk/api/content/help/cookies
This commit aims to solve that issue.
Inspired by https://github.com/alphagov/govuk-toolkit-chrome/pull/39
See https://github.com/alphagov/govuk-toolkit-chrome/issues/40

Fix content api url for help pages

---

src/popup/content_links.js

“User feedback” is more obvious than “Anonymous feedback”.

Rename anonymous feedback to user feedback

---

spec/javascripts/ab_tests_spec.js
spec/javascripts/support/jasmine.yml
src/fetch-page-data.js
src/popup.html
src/popup/ab_tests.js
src/popup/popup.css
src/popup/popup.js

Determine any A/B tests which are currently active, using the meta-tag which has been added to the page. Display this in the extension popup, making it clear which version of the page the user is seeing.
The A/B tests are added to the bottom of the extension's popup window:
If there are no active A/B tests, this section doesn't appear at all.
Note that this currently just displays the current A/B bucket. The next thing to do is add code to allow the user to change the bucket. I'm also planning to add a "Clear" button to remove the cookie or header, so the user can be reassigned to a random bucket.

Display active A/B tests, with current variant highlighted

---

spec/javascripts/ab_tests_spec.js
src/events/ab_test_settings.js
src/manifest.json
src/popup.html
src/popup/ab_tests.js
src/popup/popup.css
src/popup/popup.js

Make the A/B test buckets interactive, so that a user can select the version that they want to see. This works by appending a custom HTTP header to the request, which will only work against origin servers - it will be overridden by Varnish configuration if the request passes through the CDN. A future commit will add the same functionality using a cookie, which will work with the CDN.
Note that the selected A/B buckets are not persisted when the browser is closed. I expect this will be fine for our purposes, which is to view different versions of the page during development in Dev and Integration. We can always add persistence if it turns out to be useful - it just didn't seem worth adding it now, but let me know if you disagree!
The Production version of this will use cookies, which …

Allow users to select an A/B bucket on Integration and Staging

---

src/events/ab_test_settings.js
src/manifest.json
src/popup/popup.js

When the user selects a different A/B testing bucket, update the value of the relevant A/B cookie. This controls the user's A/B bucket on environments with a CDN, such as Production.
The custom header is still appended to the request, so that non-CDN environments still place the user in the correct bucket.

Allow users to select an A/B bucket on Production

---

src/events/ab_test_settings.js
src/popup/popup.js

This fixes a bug in which the A/B bucket values were not being displayed correctly when the extension's popup was closed and re-opened. The values were always being loaded from the metadata on the page, even when the user had chosen different buckets.
The user's chosen buckets were being used correctly to set the headers and cookie - the problem was just in the display.
Note that this fix still doesn't persist A/B buckets between browser sessions in Dev/Integration/Staging. It just persists the buckets when the popup is closed and opened.

Display correct A/B buckets when popup is reloaded

---

src/popup/popup.js

Previously, if there were content links, then the popup would be rendered twice. Most of the click handlers were being set up again, but not the new A/B bucket toggles.
This fix ensures that the popup is only rendered once when it is opened, so the click handlers are never reset.

Prevent popup from being re-rendered, since it resets click handlers

---

src/events/ab_test_settings.js

This fixes a bug which caused the extension to create an extra cookie named `ABTest-Example`, rather than updating the value of the original cookie.
This is because the extension assumed that the cookie path is always the root path, which isn't always true. This is fixed by copying the cookie `path` attribute from the original cookie, which causes the browser to overwrite the original rather than duplicate it.

Preserve cookie path when user chooses an A/B bucket

---

src/events/ab_test_settings.js

Before, we were only initializing A/B tests the first time the popup detected any A/B meta tags. This means that if a new A/B was released, it would not appear in the popup until the user restarted Chrome or the extension.
This was also a problem in the more common situation where you you switch between environments with different A/B tests defined.

Pick up new A/B tests without having to reload extension

---

src/fetch-page-data.js

The syntax of the A/B testing meta tag has been changed so that it fits the format expected by the Google Analytics code (alphagov/frontend#1110). This commit updates the tag parsing to extract the test name and current buckets from the new format.
Old format:
`<meta name="govuk:ab-test:Example:current-bucket" content="A">`
New format:
`<meta name="govuk:ab-test" content="Example:A">`
Trello:
https://trello.com/c/g9OyC7Pn/310-tell-google-analytics-about-a-b-tests

Update A/B bucket parsing to match new meta tag format

---

src/events/ab_test_settings.js
src/popup/popup.js

Call background script which stores A/B test settings from the popup script directly, rather than sending and listening for events. Events are only necessary when communicating between content and background scripts.
This is in preparation for storing environment-specific A/B test settings: using function calls rather than `chrome.runtime.onMessage` will make this easier to unit test, as well as being conceptually simpler.
https://trello.com/c/jra1OClm/320-make-it-easy-to-test-experiments-in-non-prod-environments

Simplify message passing between popup and background script

---

spec/javascripts/events/ab_bucket_store_spec.js
spec/javascripts/support/jasmine.yml
src/events/ab_bucket_store.js
src/events/ab_test_settings.js
src/manifest.json
src/popup/popup.js

This fixes issues like this:
1. Visit an A/B test page on Integration.
2. Set the bucket to B. Integration has no CDN and no A/B cookies, this just sets the header that would be sent with the request.
3. Visit the A/B page in on Production.
4. If this happens to place you in the B bucket, everything is consistent, and the extension works as  expected. But if you are placed in the A bucket, your A/B cookie will say 'A' but the extension will  show 'B'.
https://trello.com/c/jra1OClm/320-make-it-easy-to-test-experiments-in-non-prod-environments
Marked as DO NOT MERGE because it depends on on #58. If that gets merged, I'll rebase and update the merge base for this PR.

Make A/B test settings environment-specific

---

src/events/ab_test_settings.js
src/popup/popup.js

When the user selects a different A/B bucket, they almost certainly want to see that version of the page immediately. This saves them a click each time.
https://trello.com/c/jra1OClm/320-make-it-easy-to-test-experiments-in-non-prod-environments
Marked as DO NOT MERGE because it depends on on #58. If that gets merged, I'll rebase and update the merge base for this PR.

Immediately refresh page when user chooses A/B bucket

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js
src/popup/popup.css

The docs now contain pages with info on (almost) all document types on GOV.UK:
https://docs.publishing.service.gov.uk/document-types.html
https://trello.com/c/EfrOXi9L/8-create-document-type-documentation

Add link to document type documentation

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js

This commit removes business-support-finder, which has been replaced with finder-frontend.
Trello: https://trello.com/c/9O34PdXb/547-remove-business-support-finder-application

Remove business-support-finder

---

spec/javascripts/content_links_spec.js
spec/javascripts/extract_path_spec.js
src/popup/content_links.js

The [`content_api`](https://github.com/alphagov/govuk_content_api) has
been retired, and all content has been migrated to the
[`content_store`](https://github.com/alphagov/content-store).
Therefore, we can remove all references to the Content API, and rely
solely on the Content Store.
https://trello.com/c/TsUsUwD7/153-remove-documentation-on-content-api

Remove the Content API

---

Gemfile
Gemfile.lock
spec/javascripts/ab_tests_spec.js
spec/javascripts/events/ab_bucket_store_spec.js
src/events/ab_bucket_store.js
src/events/ab_test_settings.js
src/fetch-page-data.js
src/popup/ab_tests.js

This PR allows the Chrome extension to show different bucket names than just A and B. Now that we are adding functionality to `govuk_ab_testing` to rename variants, we need to allow the extension to show those. In order to know what variants we can choose from in a given A/B test, we've added a new data attribute to the analytics metatag called `data-allowed-variants` which lists the valid values. If no data attribute exists (for backwards compatibility), we default to `A` and `B`.
Here are the dependencies:
And the related PRs that need this change:
Part of: https://trello.com/c/S5jp2jih/179-setup-technical-implementation-for-a-b-testing-the-blue-box
Here is how it looks in development:

Read variant names from metatag

---

spec/javascripts/extract_path_spec.js
src/popup/extract_path.js

This is useful when other parameters have been added such as a cache-busting parameter. Previously, the Chrome extension would fail to load when other parameters were present.

Handle multiple query parameters when extracting the path

---

spec/javascripts/content_links_spec.js
spec/javascripts/extract_path_spec.js
src/popup/content_links.js
src/popup/extract_path.js

[Trello card](https://trello.com/c/7SgBCc64/696-3-fix-broken-visualise-link)
Following the separation of the start page from the rest of a smart answer flow from [1], the /visualise path has been made redundant returning 404 as a result.
PR [2], moves the /visualise path under /y (i.e /y/visualise) for the visualise tool.
This pull request updates this chrome extension so content designers can easily gain access to the visualise tool.
[1] https://github.com/alphagov/smart-answers/pull/3126
[2] https://github.com/alphagov/smart-answers/pull/3166
- User will be able to click on "SmartAnswers: Visualise":
- See the visualise page for the smart answer in question
- Will not get a page not found response

Move /visualise to /y/visualise

---

spec/javascripts/fixtures/app-c-back-to-top.html
spec/javascripts/fixtures/govuk-breadcrumbs.html
spec/javascripts/fixtures/pub-c-button.html
spec/javascripts/highlight_component_spec.js
spec/javascripts/support/jasmine-jquery.js
spec/javascripts/support/jasmine.yml
spec/javascripts/support/polyfills/String.startsWith.js
src/fetch-page-data.js
src/highlight-component.css
src/highlight-component.js
src/manifest.json
src/popup.html
src/popup/popup.css
src/popup/popup.js

We hope to encourage re-use of design elements that are documented in
the component guides [1][2] by highlighting where they exist in the
page.
The user can toggle this functionlity on from the extension popup,
which will outline all the components in the page with a label of what
it is called. Clicking within the outline will navigate the user to
its documentation.
[1] https://govuk-static.herokuapp.com/component-guide
[2] https://government-frontend.herokuapp.com/component-guide

Add function to outline GOV.UK components on page

---

src/popup.html
src/popup/popup.js

In a previous release, the selector to attach click events was updated
to split apart internal and external links. However, the links that
changed the enviornments were missed and have since stopped working.
This has been resolved by adding an 'in-popup' class to all links in
the page that change the content in the current page.

Register click events for switching environments

---

src/popup.html
src/popup/popup.css

The maximum height of the extension popup is 600px, which is visible
when a page has an active A/B test and the toggle displays in the
popup. We can save ourselves some space by combining this toggle with
the recent highlight component toggle.
Resolves https://github.com/alphagov/govuk-toolkit-chrome/issues/81

Combine A/B test and highlight component toggles together

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js

This commit changes the “Go to whitehall” link to point directly to the relevant content item in whitehall rather than the homepage. This is enabled by the `/by-content-id` route in whitehall.
Trello: https://trello.com/c/DiAmzZPL/86-link-to-whitehall-from-the-chrome-extension
Addresses https://github.com/alphagov/govuk-toolkit-chrome/issues/74

Link directly to content item in whitehall

---

README.md
spec/javascripts/content_links_spec.js
spec/javascripts/environment_spec.js
spec/javascripts/extract_path_spec.js
spec/javascripts/support/helpers.js
src/fetch-page-data.js
src/manifest.json
src/popup.html
src/popup/content_links.js
src/popup/environment.js
src/popup/extract_path.js
src/popup/popup.css
src/popup/popup.js

This PR adds compatibility with Firefox by changing some aspects of the extension while keeping compatibility with Chrome. This is possible since Firefox supports substantially the same extension API as Chrome.
Trello: https://trello.com/c/5g5lCG9G/71-make-the-chrome-extension-work-in-firefox

Make the extension compatible with Firefox

---

spec/javascripts/fixtures/gem-c-label.html
spec/javascripts/highlight_component_spec.js
src/highlight-component.js

Update the extension to include highlighting for components using the 'gem-c' namespace, i.e. components in the [govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components) gem. 
Result:

Add 'gem-c' to include component gem components

---

spec/javascripts/fixtures/meta-tags.html
spec/javascripts/highlight_component_spec.js
spec/javascripts/show_meta_tags_spec.js
src/highlight-component.js
src/popup.html
src/popup/popup.js

This adds a button to the plugin for showing meta tags in a banner at the top of the page. It can be used to see what's being sent to google analytics, and what search engines see when crawling the page.
It's equivalent to this bookmarklet: `javascript:(function()%7Bvar d %3D document.createElement(%27div%27)%3Bvar x %3D document.getElementsByTagName(%27title%27)%5B0%5D%3Bvar msg %3D %27<p><strong>title (%27%2Bx.innerHTML.length%2B%27):</strong> %27%2Bx.innerHTML%2B%27</p>%27%3Bvar ms %3D document.getElementsByTagName(%27meta%27)%3Bfor(var i%3D0%3Bi<ms.length%3Bi%2B%2B)%7Bif(null!%3D ms%5Bi%5D.getAttribute(%27name%27))%7Bvar c%3Dms%5Bi%5D.getAttribute(%27content%27)%3Bmsg%2B%3D%27<p><strong>%27%2Bms%5Bi%5D.getAttribute(%27name%27)%2B%27 (%27%2Bc.length%2B%27):</strong> …

Highlight meta tags

---

src/popup/popup.js

This commit prevents Firefox from opening certain links in both the current tab and a new tab by preventing the default link behaviour, allowing the custom behaviour to open the link in the current tab.
Fixes https://github.com/alphagov/govuk-toolkit-chrome/issues/96

Stop links opening twice

---

src/fetch-page-data.js
src/popup/popup.css
src/popup/popup.js

Someone in the content team wants to use the extension but uses screen magnification. This causes the extension window to fall off the screen. Because the height is set you can't scroll.
This PR attempts to remedy the issue by setting the height of the extension if the user's browser window is lower than 600 (the max height of the popup).
We now gain a scrollbar on the popup but that's an acceptable price to pay.

Attempt to force a scrollbar when the extension doesn't fit on screen

---

src/popup/popup.css

This adds a yellow background for focussed items. It's meant to make the extension more accessible, because it really isn't clear that you're able to tab through the menu items.
Brought to my attention by Marian in the content team.

Add proper focus color

---

src/popup/popup.css
src/popup/popup.js

This prevents the scrollbar from showing when there's nothing to scroll. Hat tip @maxgds.

Only show scrollbars when we're scrolly

---

README.md
Rakefile
src/manifest.json

This now lives on:
https://github.com/alphagov/govuk-browser-extension

Update repo name

---

spec/javascripts/fixtures/gem-c-breadcrumbs.html
spec/javascripts/fixtures/gem-c-button.html
spec/javascripts/fixtures/pub-c-button.html
spec/javascripts/highlight_component_spec.js
src/highlight-component.js

This removes the highlighting of components in Static. All of the components have been moved to the gem now, so there won't be any components from Static to highlight.
Also adds speculative linking to the Design System. `govuk-` is the prefix for patterns from the GOV.UK Design System. We're not using any components from it at the moment, but might be soon.
https://trello.com/c/pU7YINt1

Update component highlighting

---

spec/javascripts/highlight_component_spec.js
src/highlight-component.js

The gem can't differentiate global classes like `govuk-width-container` from components in the design system, so it highlights a lot of things incorrectly and links to non-existent pages on the design system site.
Removing this is not really a problem because we always wrap GOV.UK Frontend components in our own component.
https://trello.com/c/YWkUAjtN

Remove highlighting for Design System components

---

spec/javascripts/content_links_spec.js
spec/javascripts/external_links_spec.js
spec/javascripts/extract_path_spec.js
src/popup/content_links.js
src/popup/external_links.js
src/popup/extract_path.js
src/popup/popup.js

This PR:
- Adds a link to [content publisher](https://github.com/alphagov/content-publisher) for pages published by that app (cc @kevindew)
- Adds a link to [content data admin](https://github.com/alphagov/content-data-admin) for all pages (cc @pmanrubia)
- Fixes the link to topics (https://github.com/alphagov/govuk-browser-extension/issues/114)
- Links to collections publisher for step by steps
- Deeplinks to Specialist Publisher documents
- Few small fixes

Better linking to publishers

---

spec/javascripts/environment_spec.js
src/popup/environment.js

This commit changes the staging and integration URLs to point to the CDN rather than origin. It also removes the production origin link, and moves development to the end of the list.

Change origin URLs to CDN

---

src/popup/content_links.js

Changing the name of the link to describe better what will happen next. This matches the copy in the link that is used in Whitehall publisher.

Update name of the link to Content Data

---

spec/javascripts/external_links_spec.js
src/popup/external_links.js

The javascript replace function only replaces the first instance of a string by default.  By using a global regex, we can correctly convert document types like 'business_finance_support_scheme' to the partial slug 'business-finance-support-schemes'.
The error can be seen if you try to use the GOV.UK browser extension to "Edit in Specialist Publisher" any pages like https://www.gov.uk/business-finance-support/business-cash-advance-uk

Cater for multiple underscores in doc types

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js

This allows easy checking of what structured data is on a page, and whether it passes Google's validity checks.
Pages inspected via URL need to be publicly accessible, so I've limited this to production URLs.  
You can also submit snippets of HTML on the testing tool if you want to test non-live pages, but that's out of scope for this.
On GOV.UK we currently implement:
- Breadcrumb (on most pages)
- Article (on most pages)
- NewsArticle (on news pages)
- GovernmentOrganization (on organisation pages)
- HowTo (on step by step pages)
- SearchResultsPage (on search pages)
- FaqPage (on answers and guides)

Add link to structured data testing tool

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js
src/popup/environment.js

I was previewing a piece of content on the draft stack when I used the
extension to view the content item. I was confused that this took me
to the live content item on GOV.UK, rather than the content item on
integration that I wanted.
Now if you're on:
https://draft-origin.integration.publishing.service.gov.uk/guidance/check-if-your-organisation-can-get-a-govuk-domain-name
And you click 'Content item (JSON)'
Instead of https://www.gov.uk/api/content/guidance/check-if-your-organisation-can-get-a-govuk-domain-name
You're taken to:
https://draft-origin.integration.publishing.service.gov.uk/api/content/guidance/check-if-your-organisation-can-get-a-govuk-domain-name

Fixes link to content item (JSON) when viewing draft content

---

README.md

Fix broken links to Chrome web store and Firefox Add-ons. Both platforms were upgraded in the past year and the URL structure has changed.

Fix broken links to publishing platforms

---

spec/javascripts/environment_spec.js
src/popup/content_links.js
src/popup/environment.js

Currently the browser extension does not work on any of the GOVUK Account pages. 
When you click the extension icon, an unhelpful **"Loading..."** message appears and none of the features seem to be available.
Implement the changes necessary to support use of the browser extension on GOVUK Accounts, so that features such as "Design mode" or "highlight components" can be used by colleagues working on the service.
-----
https://trello.com/c/d0gHnIxQ/726-make-govuk-browser-extension-work-on-the-account-manager-pages

Enable GOVUK Browser extension on GOVUK Accounts

---

spec/javascripts/content_links_spec.js
src/popup/content_links.js

The govuk browser extension has a “Display Govspeak” menu option that shows when you visit a smart answer. But it doesn’t work, and it looks like it relies on a feature of SmartAnswers that was removed a while ago. The content team don’t use it, so it makes sense to remove it completely.
Fixes: https://github.com/alphagov/govuk-browser-extension/issues/163
Trello card: https://trello.com/c/lcZjfxq8/1838-remove-unused-display-govspeak-option-from-govuk-browser-extension

Remove 'SmartAnswers: Display GovSpeak' option

---

README.md
circle.yml
src/manifest.json

- Update manifest version
- Remove circle config, since we're not using circle
- Update readme with instructions about permissions
Includes:
- https://github.com/alphagov/govuk-browser-extension/pull/165
- https://github.com/alphagov/govuk-browser-extension/pull/161

Release 1.21.0

---

spec/javascripts/content_links_spec.js
spec/javascripts/extract_path_spec.js
src/manifest.json
src/popup/content_links.js
src/popup/extract_path.js

Content Data Admin app moved from `content-data-admin.publishing.service.gov.uk` to `content-data.publishing.service.gov.uk` years ago.

Use the canonical hostname for Content Data app.

---

src/components/highlight-component/highlight-component.js

Clicking any of the components on the page whilst using highlight component opens up two tabs: Public layout and whichever highlighted component was selected.
For some reason, when clicking the word Search on the [gov.uk](http://gov.uk/) homepage, whilst highlight components is on opens up 4 tabs.
So that the correct component guide tab opens when a component is clicked and only once.
https://trello.com/c/7MGCF3gV/2364-highlight-components

Prevent event bubbling

---

.github/workflows/ci.yml

govuk-saas-config [looks for](https://github.com/alphagov/govuk-saas-config/blob/395a713522985d7cdfc9ef5320892cace7a72042/github/lib/configure_repo.rb#L115-L120) a job named `test`, and sets this as a 'required' status check if it exists.
Defining one here means we'll ensure that tests have to pass in order for PRs to be merged, which is standard best practice.
Trello: https://trello.com/c/3CYpdFw4/3480-set-stricter-branch-protection-defaults

Rename job to `test` so it can be set as required status check

---

.github/workflows/ci.yml

This will resolve the alert at https://gds.slack.com/archives/C02L13S214K/p1714381348726429.
NB, this took a bit of effort! We were [seeing](https://github.com/alphagov/govuk-browser-extension/actions/runs/9283183060/job/25542847886?pr=196) an error with the default code analysis:
```
Extracting javascript
Extracting ruby
Finalizing javascript
Finalizing ruby
/opt/hostedtoolcache/CodeQL/2.17.1/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14567 /home/runner/work/_temp/codeql_databases/ruby
CodeQL detected code written in JavaScript/TypeScript, but not any written in Ruby. Confirm that there is some source code for Ruby in the project. For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-b …
```

Add missing SCA / SAST scans to CI

---

spec/javascripts/environment.spec.js
src/fetch-page-data.js
src/popup/content_links.js
src/popup/environment.js
src/popup/extract_path.js
src/popup/popup.js

- Overbroad matching of hostnames: `.` vs `\.`
- Overuse of `RegExp.prototype.match` where `String.prototype.includes` or `RegExp.prototype.test` suffice and better communicate the intent by returning a boolean.
- Use `Location.hostname` and not `Location.host`, because we're already assuming there isn't a port on the end (e.g. `:8080`). This avoids further complicating the (corrected) regexes.
- Where we're given a full URL as a `String` and we're trying to match on the hostname, just parse it properly with `URL`.
Should resolve:
- https://github.com/alphagov/govuk-browser-extension/security/code-scanning/1
- https://github.com/alphagov/govuk-browser-extension/security/code-scanning/2
- https://github.com/alphagov/govuk-browser-extension/security/code-scanning/3
- …

Fix regex misuse.

---

README.md

8cc2248 updated this in the Chrome section, but missed Firefox. The repo uses `main`, so this should be reflected in the link (though the current link still works)

Fix branch reference in download link

---

README.md

In its current state, and presumably since the [Manifest V3 migration](https://github.com/alphagov/govuk-browser-extension/pull/186), the extension doesn't work on Firefox. However, it can be made fully functional with a small change
When loading the extension in Firefox, the following is reported
```
There was an error during the temporary add-on installation.
Error details
background.service_worker is currently disabled
```
Firefox doesn't currently support `background.service_worker` in Manifest V3: https://bugzilla.mozilla.org/show_bug.cgi?id=1573659. This property was added when migrating to V3:
https://github.com/alphagov/govuk-browser-extension/pull/186
If you remove this section from the manifest, it will work on V3. The only caveat is that the icon won't change when on a GOV.UK …

Add instructions for Firefox V3 workaround

---

.github/workflows/ci.yml
package.json
spec/javascripts/content_blocks_component.spec.js
spec/javascripts/fixtures/content-blocks.html
spec/support/jasmine-browser.json
src/components/content-blocks-component/content-blocks-component.css
src/components/content-blocks-component/content-blocks-component.js
src/manifest_base.json
src/popup.html
src/popup/popup.js
src/service_utils/icon.js
src/service_worker.js

Trello card: https://trello.com/c/JDtjEdz0/1009-allow-govuk-browser-extension-to-highlight-content-blocks
This adds a link to the extension to highlight content blocks that are in use on a page, as well as showing a link to navigate to each block

Add content block highlighting

---

spec/javascripts/highlight_component.spec.js
src/components/highlight-component/highlight-component.js
src/fetch-page-data.js
src/manifest_base.json

A small PR to fix two problems:
- currently the extension relies on the meta tag `rendering-application` for a specific limited use case (deciding whether to show a smart answers menu item). Everything else looks for the `rendering-app` tag, so update to use that.
- currently popping up the extension (even if you do nothing else) renders all links in the page unclickable, because a listener that's used for the highlight components option is initialised and prevents defaults on all links. Update that to prevent defaults only if components are actually currently being highlighted.

Small fixes: use rendering-app and prevent click breaking
